[WIP] BLSCT Tx Factory and Verification
navcoin/navcoin pull request #131
Opened 2023-10-16 21:55 UTC by aguycalled

This PR adds functionality for the creation and verification of transactions.

It misses additional tests.

2023-12-27 22:49 UTC, gogoex requested changes
Regarding other parts I don't have enough knowledge to review in detail but looked good to me.

2023-12-27 22:49 UTC, gogoex commented on src/blsct/building_block/imp_inner_prod_arg.cpp
> +        for (size_t i = 0; i < std::min(Ls.Size(), num_rounds); ++i) {
This was my mistake. Can you just use Ls.Size() instead of std::min(...) and remove num_rounds from the function signature?

2023-12-27 22:49 UTC, gogoex commented on src/blsct/range_proof/bulletproofs/range_proof_logic.cpp
> +    int i = -1;
I think it's better to drop this and change the for loop in line 375 to

```c++
for (size_t i=0; i < reqs.size(); ++i) {
```

then remove `i++` in line 379 and `(size_t)` in line 426.

2023-12-27 22:49 UTC, gogoex commented on src/blsct/building_block/imp_inner_prod_arg.cpp
> +    if (Rs.Size() == Ls.Size()) {
This check should have been done earlier in the verification process. Can you remove this line and add:

```c++
 if (proof.Ls.size() != proof.Rs.size() return false;
```

at the beginning of `bool SetMemProofProver<T>::Verify` and also change `bool RangeProofLogic<T>::VerifyProofs` so that 

```c++
if (p.proof.Ls.size() != p.proof.Rs.size()) return false;
```

becomes the first line of the for-loop block. That is,

```c++
    using Scalar = typename T::Scalar;
    using Scalars = Elements<Scalar>;

    for (const RangeProofWithTranscript<T>& p : proof_transcripts) {
        if (p.proof.Ls.size() != p.proof.Rs.size()) return false;
```

2023-12-28 05:19 UTC, mxaddict reviewed
I have a few questions, but other than that looks good, some of the blsct related code went over my head though 😄

2023-12-28 05:19 UTC, mxaddict commented on test/functional/wallet_create_tx.py
> -
Is this test no longer necessary?

2023-12-28 17:49 UTC, aguycalled commented on src/blsct/private_key.cpp
> +    } // namespace blsct
solved

2023-12-28 21:18 UTC, gogoex approved these changes

2023-12-28 22:03 UTC, mxaddict approved these changes

2023-12-28 22:03 UTC, mxaddict commented
I think we wait for the `[multiprocess, i686, DEBUG] [focal]` build to pass, then this should be ready for merge.

2023-12-28 23:23 UTC, merged