rpc: add dumpmnemonic to export key passphrase.
navcoin/navcoin pull request #69
Opened 2022-09-03 10:38 UTC by sinetek

As part of bringing mnemonic support to the wallet, add an rpc call 'dumpmnemonic'.  Works with legacy wallet types.

2022-09-03 15:12 UTC, aguycalled commented on src/Makefile.am
> +  crypto/external/hmac_sha256.c \
all the files added in `crypto/external`, except `pkcs5_pbkdf2.*` and `zeroize.*`, are already present in `crypto/`. do we need them duplicated for any specific reason?

2022-09-03 15:17 UTC, aguycalled requested changes

2022-09-03 15:17 UTC, aguycalled commented on src/mnemonic/mnemonic.cpp
> +/**
I think this implementation is taken from the old codebase, which does not completely conform to BIP-39 as it does not support the use of passphrases.

The passphrase should be concatenated to the mnemonic prefix string (`mnemonic`) to get the salt.

From https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki:

```
To create a binary seed from the mnemonic, we use the PBKDF2 function with a mnemonic sentence (in UTF-8 NFKD) used as the password and the string "mnemonic" + passphrase (again in UTF-8 NFKD) used as the salt.
```

2022-09-03 15:20 UTC, aguycalled commented
This PR does not include any test. I'd suggest adding both functional (`test/functional`) and unit (`src/test`) tests.

2022-09-03 15:24 UTC, aguycalled commented on src/wallet/rpc/backup.cpp
> +        throw JSONRPCError(RPC_WALLET_ERROR, "Could not obtain spk_man.");
In which scenario is this hit? If it is depending on the wallet type (legacy vs descriptors), we could make the exception more descriptive and indicate the reason.

2022-09-03 15:24 UTC, aguycalled commented on src/wallet/rpc/backup.cpp
> +                "\nReveals the mnemonic for the current master private key.\n"
The help string could indicate to the user which wallets are compatible with the command.

2022-09-03 15:38 UTC, sinetek commented on src/wallet/rpc/backup.cpp
> +        throw JSONRPCError(RPC_WALLET_ERROR, "Could not obtain spk_man.");
it could also happen if there is no spk manager, which is possible if the wallet is blank.

2022-09-03 15:39 UTC, sinetek commented on src/wallet/rpc/backup.cpp
> +                "\nReveals the mnemonic for the current master private key.\n"
Maybe, that's implementation specific and could change in the future with us forgetting to update the documentation text.

2022-09-03 15:40 UTC, sinetek commented on src/Makefile.am
> +  crypto/external/hmac_sha256.c \
I don't think there is much overlap between these, despite the name of the files. From a cursory look.

2022-09-03 15:44 UTC, sinetek commented on src/mnemonic/mnemonic.cpp
> +/**
ok so that has to be added in.

2022-09-03 15:48 UTC, mxaddict commented on src/mnemonic/mnemonic.h
> + * @param sentence
For some reason, this line is causing an error in CI builds:
```
./mnemonic/mnemonic.h:97:18: error: empty paragraph passed to '@param' command [-Werror,-Wdocumentation]
 * @param sentence
   ~~~~~~~~~~~~~~^
1 error generated.
```

I think you need to provide a description after the `@param` name

2022-09-03 16:05 UTC, aguycalled commented on src/wallet/rpc/backup.cpp
> +                "\nReveals the mnemonic for the current master private key.\n"
We should keep it descriptive imo and aim to update if circumstances change.

2022-09-03 16:17 UTC, aguycalled commented on src/Makefile.am
> +  crypto/external/hmac_sha256.c \
I had a look now and they seem to be just different implementations of the same cryptographic protocols. I think we should adapt it to use those already included in `src/crypto` when possible.

2022-09-03 16:39 UTC, aguycalled commented on src/wallet/rpc/backup.cpp
> +        throw JSONRPCError(RPC_WALLET_ERROR, "Could not obtain spk_man.");
Makes sense.

2022-09-04 09:10 UTC, sinetek commented on src/mnemonic/mnemonic.h
> + * @param sentence
just going to remove it.

2022-09-04 09:36 UTC, sinetek commented
hey @aguycalled is it possible to get the passphrase from the seed key? it looks to be a lossy operation when recovering, you'd not be able to dump that or am I missing something

2022-09-04 09:38 UTC, aguycalled commented
yes, the passphrase is not stored nor dump-able

2022-09-04 10:01 UTC, sinetek commented
should we just store it?

2022-09-04 10:58 UTC, aguycalled commented
it's intended to function like a 2-fa to the seed words, storing it would break this use. its designed to not be stored, and to not be dumped with the seed words

2022-09-04 11:00 UTC, mxaddict commented
> 

I agree with this.

The password/passphrase should only be used to create the salt, and the salt is what's stored no?

And on export, the user needs to remember the passphrase himself

2022-09-08 17:59 UTC, aguycalled commented on src/blsct/arith/elements.h
> +    Elements() {}
Could you elaborate on why this change was needed?

2022-09-09 10:23 UTC, closed without merging